server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
}

server {
        listen 443 ssl;
        server_name wf1-wfdm-opensearch-int.bcwildfireservices.com;
        location / {
                proxy_pass_request_headers on;
                proxy_pass_request_body on;
                proxy_pass https://search-wf1-wfdm-opensearch-int-wf4q3qaztsvtg3bl47u6cwrue4.ca-central-1.es.amazonaws.com/;
                proxy_set_header Host $http_host;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
                proxy_request_buffering off;
}
        ssl_certificate /etc/letsencrypt/live/wf1-wfdm-opensearch-int.bcwildfireservices.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/wf1-wfdm-opensearch-int.bcwildfireservices.com/privkey.pem;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
}

server {
        listen 443 ssl;
        server_name wf1-wfdm-opensearch-dlv.bcwildfireservices.com;
        location / {
                proxy_pass_request_headers on;
                proxy_pass_request_body on;
                proxy_pass https://search-wf1-wfdm-opensearch-dlv-kkbolgrw43mwl7krvrahnkzaxu.ca-central-1.es.amazonaws.com/;
                proxy_set_header Host $http_host;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
                proxy_request_buffering off;
}
        ssl_certificate /etc/letsencrypt/live/wf1-wfdm-opensearch-dlv.bcwildfireservices.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/wf1-wfdm-opensearch-dlv.bcwildfireservices.com/privkey.pem;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
}

server {
        listen 443 ssl;
        server_name wf1-wfdm-opensearch-tst.bcwildfireservices.com;
        location / {
                proxy_pass_request_headers on;
                proxy_pass_request_body on;
                proxy_pass https://search-wf1-wfdm-opensearch-tst-zcdf3dkpzg5eauywv2o36j5u2m.ca-central-1.es.amazonaws.com/;
                proxy_set_header Host $http_host;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
                proxy_request_buffering off;
}
        ssl_certificate /etc/letsencrypt/live/wf1-wfdm-opensearch-tst.bcwildfireservices.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/wf1-wfdm-opensearch-tst.bcwildfireservices.com/privkey.pem;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
}

server {
        listen 443 ssl;
        server_name wf1-wfdm-opensearch-prd.bcwildfireservices.com;
        location / {
                proxy_pass_request_headers on;
                proxy_pass_request_body on;
                proxy_pass https://search-wf1-wfdm-opensearch-prd-uu3gm35rfnr3tyn6wwnbs5qthu.ca-central-1.es.amazonaws.com/;
                proxy_set_header Host $http_host;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
                proxy_request_buffering off;
}
        ssl_certificate /etc/letsencrypt/live/wf1-wfdm-opensearch-prd.bcwildfireservices.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/wf1-wfdm-opensearch-prd.bcwildfireservices.com/privkey.pem;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
}